export const Topics = {
  USER_CREATED: "user.created",
  DRIVER_PROFILE_CREATE: "driver.profile.create",
  RIDER_PROFILE_CREATE: "rider.profile.create",
  BOOKING_CREATED: "booking.created",
  TRIP_COMPLETED: "trip.completed",
  TRIP_CREATE_COMMAND: 'trip.create.command',
  TRIP_CANCELLED: "trip.cancelled",
  TRIP_CREATE_REPLY: "trip.create.reply",
  TRIP_STARTED: "trip.started",
  DRIVER_RATED: "driver.rated",
  RIDE_REQUESTED: "ride.requested",
  RIDE_CANCELLED: "ride.cancelled",
  DRIVER_ONLINE: "driver.online",
  DRIVER_OFFLINE: "driver.offline",
  FARE_CALCULATE_COMMAND: "fare.calculate.command",
  FARE_CALCULATE_REPLY: "fare.calculate.reply",
  DRIVER_FIND_COMMAND: "driver.find.command",
  DRIVER_FIND_REPLY: "driver.find.reply",
  DRIVER_RELEASE_COMMAND: "driver.release.command",
  BOOKING_CONFIRMED: "booking.confirmed",
  BOOKING_FAILED: "booking.failed",
} as const;
